### ISSUE TITLE
instant-generics-0.4.1 does not compile with GHC 7.10.1

### ISSUE THREAD

**Issue by peti** [dreixel/instant-generics#2]
Citing from http://hydra.cryp.to/build/959954/nixlog/1/raw:

```
src/Generics/Instant/TH.hs:94:12:
    Not in scope: data constructor ‘EqualP’
    Perhaps you meant variable ‘equalP’ (imported from Language.Haskell.TH)

src/Generics/Instant/TH.hs:110:15:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH),
      ‘ClassI’ (imported from Language.Haskell.TH),
      variable ‘classP’ (imported from Language.Haskell.TH)

src/Generics/Instant/TH.hs:325:14:
    Not in scope: data constructor ‘EqualP’
    Perhaps you meant variable ‘equalP’ (imported from Language.Haskell.TH)

src/Generics/Instant/TH.hs:329:14:
    Not in scope: data constructor ‘EqualP’
    Perhaps you meant variable ‘equalP’ (imported from Language.Haskell.TH)
```

**Comment by dreixel** [comment]
A new version has been released which should fix this. Thanks for reporting!
